# Generated by Django 3.1 on 2020-08-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingCategory', to='auctions.category'),
        ),
    ]
